//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeportiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public int EquipoId { get; set; }
        public string EquipoNombre { get; set; }
        public int DeporteId { get; set; }
    
        public virtual Deporte Deporte { get; set; }
    }
}
