//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeportiva.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Evento
    {
        public int EventoId { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Lugar { get; set; }
        public string Equipo1 { get; set; }
        public string Equipo2 { get; set; }
    }
}
