//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeportiva.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_GestionDeportivaEntities : DbContext
    {
        public BD_GestionDeportivaEntities()
            : base("name=BD_GestionDeportivaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deporte> Deportes { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Evento> Eventos { get; set; }
        public virtual DbSet<Sede> Sedes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
